{
  TargetSite: Void MoveNext(),
  Message: Test exception,
  InnerException: null,
  HelpLink: null,
  Source: AppFact.SerilogOpenSearchSink.Tests,
  HResult: -2146233088,
  StackTrace:    at AppFact.SerilogOpenSearchSink.Tests.Serialization.ExceptionSerializationTests.CanSerializeSimpleException() in /old_root/@{ProjectDirectory}Serialization/ExceptionSerializationTests.cs:line 14
}