{
  TargetSite: Void MoveNext(),
  Message: Test exception1,
  InnerException: null,
  HelpLink: null,
  Source: AppFact.SerilogOpenSearchSink.Tests,
  HResult: -2146233088,
  StackTrace:    at AppFact.SerilogOpenSearchSink.Tests.Serialization.ExceptionSerializationTests.CanSerializeSimpleException() in {SolutionDirectory}/AppFact.SerilogOpenSearchSink.Tests/Serialization/ExceptionSerializationTests.cs:line 14
}